AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  movieApi

  Sample SAM Template for movieApi

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20
    Environment:
      Variables:
        MOVIES_TABLE: !Ref MoviesTable

Resources:
  CreatMovieFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MovieFunction
      Handler: edu.uchicago.caor.movies.CreateMovieLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: POST
  ReadMoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: MovieFunction
      Handler: edu.uchicago.caor.movies.ReadMoviesLambda::handleRequest
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: GET