AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  movieApi

  Sample SAM Template for movieApi

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: MovieFunction
      Handler: edu.uchicago.caor.movies.CreateMovieLambda::handleRequest
      Runtime: java11
      MemorySize: 512
      Timeout: 20
      Events:
        PostMovie:
          Type: Api
          Properties:
            Path: /movies
            Method: POST
